# Generated by Django 4.1.2 on 2022-11-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_rename_name_subject_title_subject_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='content',
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(default='this is description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='assignment 1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10000)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to='lms.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('answer', models.CharField(blank=True, max_length=10000, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.assignment')),
            ],
        ),
    ]
